#!/usr/bin/env python3
"""Generate one authoritative phase release directory after real tests/builds complete."""
from __future__ import annotations

import argparse
import csv
import datetime as dt
import hashlib
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
FINAL_STATUSES = {"IMPLEMENTED", "DEFERRED_WITH_REASON", "BLOCKED_EXTERNAL"}
DESIGN_SYSTEM_VERSION = "YL-DS-1.2.0"


def utc_now() -> str:
    return dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds")


def run(command: list[str]) -> str:
    try:
        return subprocess.check_output(
            command, cwd=ROOT, text=True, stderr=subprocess.STDOUT
        ).strip()
    except Exception as exc:
        return f"unknown ({exc})"


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def load_yaml(path: Path) -> dict:
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def phase_states(phase: str) -> list[dict[str, str]]:
    pages = (load_yaml(ROOT / "contracts" / "ui-page-catalog.yaml").get("pages") or [])
    selected_pages = {page["page_id"] for page in pages if phase in (page.get("phases") or [])}
    with (ROOT / "contracts" / "ui-state-catalog.csv").open(
        encoding="utf-8-sig", newline=""
    ) as handle:
        rows = list(csv.DictReader(handle))
    return [row for row in rows if row.get("page_id") in selected_pages]


def mockups_by_state() -> dict[str, dict[str, str]]:
    with (ROOT / "contracts" / "mockup-manifest.csv").open(
        encoding="utf-8-sig", newline=""
    ) as handle:
        return {row["state_id"]: row for row in csv.DictReader(handle)}


def require_deployment_evidence(path: Path | None, self_test: bool, phase: str) -> tuple[str, str]:
    if self_test:
        content = f"""# DEPLOYMENT

- Phase: {phase}
- Deployment result: SELF_TEST_ONLY
- Health check result: PASS
- Rollback result: NOT_APPLICABLE
- Environment: isolated package self-test
- Evidence source: generated by scripts/15_SELF_TEST_PACKAGE.py

This record validates the release-control workflow only. It is not evidence that YLVEN application services were deployed.
"""
        return content, "package-self-test"
    if path is None or not path.is_file():
        expected = ROOT / "status" / f"{phase}_DEPLOYMENT_EVIDENCE.md"
        raise SystemExit(
            "Real release requires deployment evidence. Copy "
            f"templates/DEPLOYMENT_RECORD_TEMPLATE.md to {expected.relative_to(ROOT)}, "
            "fill actual staging/NOT_APPLICABLE evidence, then rerun release."
        )
    content = path.read_text(encoding="utf-8", errors="replace").strip()
    if len(content) < 200:
        raise SystemExit(f"Deployment evidence is too brief: {path}")
    required_patterns = {
        "Deployment result": r"(?im)^-\s*Deployment result:\s*(SUCCESS|NOT_APPLICABLE)\s*$",
        "Health check result": r"(?im)^-\s*Health check result:\s*(PASS|NOT_APPLICABLE)\s*$",
        "Rollback result": r"(?im)^-\s*Rollback result:\s*(PASS|NOT_APPLICABLE)\s*$",
    }
    for name, pattern in required_patterns.items():
        if not re.search(pattern, content):
            raise SystemExit(
                f"Deployment evidence {path} must contain '- {name}: SUCCESS/PASS/NOT_APPLICABLE' as applicable."
            )
    return content + "\n", str(path.resolve())


def clean_previous_output(output: Path, phase: str) -> None:
    names = {
        f"YLVEN-{phase}-test.apk", "原功能清单.md", "功能完成对比清单.md",
        "完整测试清单.md", "自动化测试报告.md", "变更记录.md", "部署证据.md",
        "所有者操作项.md", "所有者验收.md", "构建信息.json", "CI来源证明.json",
        "校验文件_SHA256.txt", "截图索引.csv", "视觉差异报告.md",
        "界面合同报告.json", "管理后台实测证据.md", "覆盖安装证据.md",
        # Remove legacy English aliases when regenerating an existing output.
        "FEATURES.md", "TESTS.md", "CHANGELOG.md", "DEPLOYMENT.md",
        "OWNER_ACTIONS.md", "OWNER_ACCEPTANCE.md", "BUILD_INFO.json",
        "CI_PROVENANCE.json", "SHA256SUMS.txt", "UI_SCREENSHOT_INDEX.csv",
        "VISUAL_DIFF_REPORT.md", "UI_CONTRACT_REPORT.json",
    }
    for name in names:
        candidate = output / name
        if candidate.exists():
            if candidate.is_dir():
                shutil.rmtree(candidate)
            else:
                candidate.unlink()
    screenshot_dir = output / "截图"
    if screenshot_dir.exists():
        shutil.rmtree(screenshot_dir)
    legacy_screenshot_dir = output / "screenshots"
    if legacy_screenshot_dir.exists():
        shutil.rmtree(legacy_screenshot_dir)


def write_self_test_ui(output: Path, phase: str, states: list[dict[str, str]]) -> dict:
    fields = [
        "state_id", "page_id", "mockup_path", "mockup_sha256",
        "runtime_screenshot_path", "runtime_sha256", "device_width_dp",
        "theme", "font_scale", "status", "notes",
    ]
    with (output / "截图索引.csv").open(
        "w", encoding="utf-8-sig", newline=""
    ) as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        for row in states:
            writer.writerow({
                "state_id": row["state_id"],
                "page_id": row["page_id"],
                "mockup_path": row["mockup_path"],
                "mockup_sha256": "SELF_TEST_ONLY",
                "runtime_screenshot_path": "SELF_TEST_ONLY",
                "runtime_sha256": "SELF_TEST_ONLY",
                "device_width_dp": "360",
                "theme": "light",
                "font_scale": "1.0",
                "status": "SELF_TEST_ONLY",
                "notes": "Release-control self-test only; no visual implementation is claimed.",
            })
    (output / "视觉差异报告.md").write_text(
        "# YLVEN 界面视觉差异报告\n\n"
        f"- Phase: {phase}\n"
        f"- Design system: {DESIGN_SYSTEM_VERSION}\n"
        "- Result: SELF_TEST_ONLY\n\n"
        "This report exists only to exercise the release-control workflow. No mockup approval, runtime screenshot, pixel comparison or visual implementation is claimed.\n",
        encoding="utf-8",
    )
    report = {
        "schema_version": "1.0",
        "phase": phase,
        "design_system_version": DESIGN_SYSTEM_VERSION,
        "result": "SELF_TEST_ONLY",
        "expected_state_count": len(states),
        "screenshot_count": 0,
        "approved_mockup_count": 0,
        "unexplained_difference_count": 0,
        "generated_at": utc_now(),
    }
    (output / "界面合同报告.json").write_text(
        json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    return report


def write_real_ui(output: Path, phase: str, states: list[dict[str, str]], evidence_root: Path | None) -> dict:
    if evidence_root is None or not evidence_root.is_dir():
        expected = ROOT / "build" / "ui-evidence" / phase
        raise SystemExit(
            "Real phase release requires complete UI evidence at "
            f"{expected} (or pass --ui-evidence-root). It must contain screenshots/<StateID>.png "
            "and VISUAL_DIFF_REPORT.md."
        )

    gate = subprocess.run(
        [sys.executable, str(Path(__file__).resolve().parents[0] / "20_CHECK_UI_VISUAL_GATE.py"), "--phase", phase],
        cwd=ROOT, text=True, capture_output=True,
    )
    if gate.returncode != 0:
        raise SystemExit("Visual gate failed before release:\n" + (gate.stdout + gate.stderr).strip())

    mockups = mockups_by_state()
    screenshot_dir = output / "截图"
    screenshot_dir.mkdir(parents=True, exist_ok=True)
    fields = [
        "state_id", "page_id", "mockup_path", "mockup_sha256",
        "runtime_screenshot_path", "runtime_sha256", "device_width_dp",
        "theme", "font_scale", "status", "notes",
    ]
    index_rows: list[dict[str, str]] = []
    for row in states:
        state_id = row["state_id"]
        source_candidates = [
            evidence_root / "screenshots" / f"{state_id}.png",
            evidence_root / f"{state_id}.png",
        ]
        source = next((candidate for candidate in source_candidates if candidate.is_file()), None)
        if source is None:
            raise SystemExit(f"Missing runtime screenshot for {state_id}; expected {source_candidates[0]}")
        destination = screenshot_dir / f"{state_id}.png"
        shutil.copy2(source, destination)
        mockup = mockups.get(state_id)
        if not mockup:
            raise SystemExit(f"Missing mockup manifest row for {state_id}")
        index_rows.append({
            "state_id": state_id,
            "page_id": row["page_id"],
            "mockup_path": mockup["relative_path"],
            "mockup_sha256": mockup["sha256"].lower(),
            "runtime_screenshot_path": f"截图/{destination.name}",
            "runtime_sha256": sha256(destination),
            "device_width_dp": "360" if row["surface"] == "ANDROID" else "1440px-canonical",
            "theme": "light",
            "font_scale": "1.0",
            "status": "PASS",
            "notes": "Compared against approved state mockup and locked numeric contract.",
        })
    with (output / "截图索引.csv").open(
        "w", encoding="utf-8-sig", newline=""
    ) as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        writer.writerows(index_rows)

    diff_source = evidence_root / "视觉差异报告.md"
    if not diff_source.is_file():
        diff_source = evidence_root / "VISUAL_DIFF_REPORT.md"
    if not diff_source.is_file():
        raise SystemExit(f"Missing visual diff report: {diff_source}")
    diff_text = diff_source.read_text(encoding="utf-8", errors="replace")
    markers = [
        rf"(?im)^-\s*Phase:\s*{re.escape(phase)}\s*$",
        rf"(?im)^-\s*Design system:\s*{re.escape(DESIGN_SYSTEM_VERSION)}\s*$",
        r"(?im)^-\s*Result:\s*PASS\s*$",
    ]
    if not all(re.search(pattern, diff_text) for pattern in markers):
        raise SystemExit(
            "视觉差异报告.md must contain exact Phase, Design system and '- Result: PASS' markers."
        )
    missing_state_rows = [row["state_id"] for row in states if row["state_id"] not in diff_text]
    if missing_state_rows:
        raise SystemExit(
            "VISUAL_DIFF_REPORT.md is missing state rows: " + ", ".join(missing_state_rows[:20])
        )
    shutil.copy2(diff_source, output / "视觉差异报告.md")
    report = {
        "schema_version": "1.0",
        "phase": phase,
        "design_system_version": DESIGN_SYSTEM_VERSION,
        "result": "PASS",
        "expected_state_count": len(states),
        "screenshot_count": len(index_rows),
        "approved_mockup_count": len(index_rows),
        "unexplained_difference_count": 0,
        "evidence_root": str(evidence_root.resolve()),
        "generated_at": utc_now(),
    }
    (output / "界面合同报告.json").write_text(
        json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    return report


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--phase", required=True, choices=[f"P{i:02d}" for i in range(14)])
    parser.add_argument("--apk", required=True)
    parser.add_argument("--test-log", required=True)
    parser.add_argument("--out", required=True)
    parser.add_argument("--android-task", default="unknown")
    parser.add_argument("--deployment-evidence")
    parser.add_argument("--upgrade-evidence")
    parser.add_argument("--ui-evidence-root")
    parser.add_argument("--self-test-fixture", action="store_true")
    args = parser.parse_args()

    phase = args.phase
    apk = Path(args.apk).resolve()
    test_log_path = Path(args.test_log).resolve()
    output = Path(args.out).resolve()
    output.mkdir(parents=True, exist_ok=True)

    if not apk.is_file():
        raise SystemExit(f"APK does not exist: {apk}")
    if not test_log_path.is_file() or test_log_path.stat().st_size == 0:
        raise SystemExit(f"A non-empty test/build log is required: {test_log_path}")
    normalized_apk = str(apk).replace("\\", "/").lower()
    if not args.self_test_fixture and "/build/outputs/apk/" not in normalized_apk:
        raise SystemExit("Real release APK must originate under build/outputs/apk.")

    status = load_yaml(ROOT / "status" / f"{phase}_FEATURE_STATUS.yaml")
    status_entries = status.get("features") or []
    for entry in status_entries:
        current = entry.get("status")
        if current not in FINAL_STATUSES:
            raise SystemExit(f"{entry.get('feature_id')} is not in a final release status: {current}")
        if current == "IMPLEMENTED" and not (entry.get("evidence") or []):
            raise SystemExit(f"{entry.get('feature_id')} is IMPLEMENTED without evidence")
        if current != "IMPLEMENTED" and not str(entry.get("reason", "")).strip():
            raise SystemExit(f"{entry.get('feature_id')} requires a concrete reason")

    feature_map = load_yaml(ROOT / "contracts" / "feature-map.yaml").get("features") or []
    names = {feature["feature_id"]: feature["name"] for feature in feature_map}
    deployment_content, deployment_source = require_deployment_evidence(
        Path(args.deployment_evidence).resolve() if args.deployment_evidence else None,
        args.self_test_fixture,
        phase,
    )
    states = phase_states(phase)
    if not states:
        raise SystemExit(f"No UI state contracts are bound to {phase}")

    clean_previous_output(output, phase)
    target_apk = output / f"YLVEN-{phase}-test.apk"
    shutil.copy2(apk, target_apk)

    feature_lines = [
        "# FEATURES", "", f"- Phase: {phase}", f"- Generated: {utc_now()}", "",
        "| Feature ID | 功能 | 状态 | 原因/证据 |",
        "|---|---|---|---|",
    ]
    for entry in status_entries:
        detail = entry.get("reason") or "; ".join(entry.get("evidence") or []) or "—"
        detail = str(detail).replace("|", "/").replace("\n", " ")
        feature_lines.append(
            f"| `{entry['feature_id']}` | {names.get(entry['feature_id'], '')} | "
            f"{entry['status']} | {detail} |"
        )
    original_source = ROOT / "docs" / "delivery" / f"{phase}_原功能清单.md"
    comparison_source = ROOT / "docs" / "delivery" / f"{phase}_功能完成对比清单.md"
    checklist_source = ROOT / "docs" / "delivery" / f"{phase}_完整测试清单.md"
    dns_source = ROOT / "docs" / "delivery" / f"{phase}_域名DNS状态.md"
    admin_source = ROOT / "docs" / "delivery" / f"{phase}_管理后台实测证据.md"
    upgrade_source = Path(args.upgrade_evidence).resolve() if args.upgrade_evidence else None
    required_sources = (original_source, comparison_source, checklist_source, dns_source, admin_source)
    if not args.self_test_fixture:
        missing = [str(path.relative_to(ROOT)) for path in required_sources if not path.is_file()]
        if upgrade_source is None or not upgrade_source.is_file():
            missing.append("--upgrade-evidence <真实覆盖安装证据文件>")
        if missing:
            raise SystemExit("Real release is missing Chinese owner documents: " + ", ".join(missing))
    if original_source.is_file():
        shutil.copy2(original_source, output / "原功能清单.md")
    else:
        (output / "原功能清单.md").write_text("\n".join(feature_lines) + "\n", encoding="utf-8")
    if comparison_source.is_file():
        shutil.copy2(comparison_source, output / "功能完成对比清单.md")
    else:
        (output / "功能完成对比清单.md").write_text("\n".join(feature_lines) + "\n", encoding="utf-8")

    test_log = test_log_path.read_text(encoding="utf-8", errors="replace")
    tests = (
        "# TESTS\n\n"
        f"- Phase: {phase}\n"
        f"- Source log: `{test_log_path}`\n"
        f"- Generated: {utc_now()}\n"
        f"- Self-test fixture: {str(args.self_test_fixture).lower()}\n"
        "- Release command result: PASS\n\n"
        "```text\n"
        f"{test_log[-300000:]}\n"
        "```\n"
    )
    if checklist_source.is_file():
        shutil.copy2(checklist_source, output / "完整测试清单.md")
    else:
        (output / "完整测试清单.md").write_text(tests, encoding="utf-8")
    (output / "自动化测试报告.md").write_text(tests.replace("# TESTS", "# 自动化测试报告"), encoding="utf-8")
    if dns_source.is_file():
        shutil.copy2(dns_source, output / "域名DNS状态.md")
    else:
        (output / "域名DNS状态.md").write_text(
            f"# {phase} 域名DNS状态\n\n- 阶段：{phase}\n- 结果：SELF_TEST_ONLY\n",
            encoding="utf-8",
        )
    if upgrade_source is not None and upgrade_source.is_file():
        shutil.copy2(upgrade_source, output / "覆盖安装证据.md")
    else:
        (output / "覆盖安装证据.md").write_text(
            f"# 覆盖安装证据\n\n- 阶段：{phase}\n- 结果：SELF_TEST_ONLY\n",
            encoding="utf-8",
        )
    shutil.copy2(output / "原功能清单.md", output / "计划功能清单.md")
    shutil.copy2(output / "功能完成对比清单.md", output / "已完成功能清单.md")

    commit = run(["git", "rev-parse", "HEAD"])
    short_commit = run(["git", "rev-parse", "--short", "HEAD"])
    if not args.self_test_fixture and not re.fullmatch(r"[0-9a-fA-F]{40,64}", commit):
        raise SystemExit(
            "A real release requires a Git commit. Initialize the repository, commit the phase implementation, then rerun."
        )
    recent_changes = run(["git", "log", "-20", "--pretty=format:- %h %s"])
    (output / "变更记录.md").write_text(
        f"# 变更记录\n\n- 阶段：{phase}\n- Commit：`{commit}`\n- 生成时间：{utc_now()}\n\n"
        f"## 最近提交\n{recent_changes}\n\n"
        "## 已知限制\n详见原功能清单.md、功能完成对比清单.md和所有者操作项.md。\n",
        encoding="utf-8",
    )
    (output / "部署证据.md").write_text(deployment_content, encoding="utf-8")

    owner_actions = ROOT / "OWNER_ACTIONS.md"
    if owner_actions.exists():
        shutil.copy2(owner_actions, output / "所有者操作项.md")
    else:
        (output / "所有者操作项.md").write_text(
            "# 所有者操作项\n\n当前没有待所有者处理的事项。\n", encoding="utf-8"
        )

    if args.self_test_fixture:
        ui_report = write_self_test_ui(output, phase, states)
    else:
        ui_report = write_real_ui(
            output, phase, states,
            Path(args.ui_evidence_root).resolve() if args.ui_evidence_root else None,
        )

    pinned = (ROOT / "speckit" / "profile" / "SPECKIT_PINNED_VERSION").read_text(
        encoding="utf-8"
    ).strip()
    build_info = {
        "schema_version": "1.6.0",
        "phase": phase,
        "version_identity_source": "contracts/release-version-matrix.yaml",
        "git_commit": commit,
        "git_short": short_commit,
        "generated_at": utc_now(),
        "apk_name": target_apk.name,
        "apk_size": target_apk.stat().st_size,
        "apk_sha256": sha256(target_apk),
        "source_apk": str(apk),
        "artifact_origin": "self-test-fixture" if args.self_test_fixture else "gradle",
        "android_task": args.android_task,
        "self_test_fixture": args.self_test_fixture,
        "deployment_evidence_source": deployment_source,
        "spec_kit_pinned_version": pinned,
        "design_system_version": DESIGN_SYSTEM_VERSION,
        "ui_contract_result": ui_report["result"],
        "ui_expected_state_count": ui_report["expected_state_count"],
        "ui_screenshot_count": ui_report["screenshot_count"],
    }
    (output / "构建信息.json").write_text(
        json.dumps(build_info, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    (output / "CI来源证明.json").write_text(
        json.dumps({
            "phase": phase,
            "commit_sha": commit,
            "apk": target_apk.name,
            "apk_sha256": sha256(target_apk),
            "artifact_origin": build_info["artifact_origin"],
            "test_log": str(test_log_path),
            "generated_at": utc_now(),
        }, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )

    acceptance_template = (ROOT / "templates" / "OWNER_ACCEPTANCE_TEMPLATE.md").read_text(
        encoding="utf-8"
    )
    acceptance_template = acceptance_template.replace("Pxx", phase).replace(
        "YLVEN-Pxx-test.apk", target_apk.name
    )
    if "UI visual acceptance" not in acceptance_template:
        acceptance_template += (
            "\n## UI visual acceptance\n\n"
            f"- Design system: {DESIGN_SYSTEM_VERSION}\n"
            "- All bound page states checked against approved mockups: PENDING\n"
            "- Visual differences reviewed: PENDING\n"
        )
    (output / "所有者验收.md").write_text(acceptance_template, encoding="utf-8")
    if admin_source.is_file():
        shutil.copy2(admin_source, output / "管理后台实测证据.md")
    elif args.self_test_fixture:
        (output / "管理后台实测证据.md").write_text(
            "# 管理后台实测证据\n\n- 测试人：Codex\n- 网址：SELF_TEST_ONLY\n- 真实 API 数据：SELF_TEST_ONLY\n- 审计记录：SELF_TEST_ONLY\n",
            encoding="utf-8",
        )

    immutable = sorted(
        [
            path for path in output.rglob("*")
            if path.is_file()
            and path.name not in {"校验文件_SHA256.txt", "所有者验收.md"}
        ],
        key=lambda item: item.relative_to(output).as_posix(),
    )
    (output / "校验文件_SHA256.txt").write_text(
        "".join(
            f"{sha256(path)}  {path.relative_to(output).as_posix()}\n"
            for path in immutable
        ),
        encoding="utf-8",
    )
    print(
        f"Release generated for {phase}: {output} "
        f"({len(states)} UI states; UI result={ui_report['result']})"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
