server {
    listen 80;
    server_name ai-admin.orbexa.cc;

    root /www/wwwroot/ai-admin.orbexa.cc/current;
    index index.html;

    location ^~ /.well-known/acme-challenge/ {
        root /www/wwwroot/ai-admin.orbexa.cc;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    access_log /www/wwwlogs/ai-admin.orbexa.cc.log;
    error_log /www/wwwlogs/ai-admin.orbexa.cc.error.log;
}
