server {
    listen 80;
    server_name auth.orbexa.cc;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 404;
    }

    access_log /www/wwwlogs/auth.orbexa.cc.log;
    error_log /www/wwwlogs/auth.orbexa.cc.error.log;
}
